default: &default
  adapter: postgresql
  encoding: utf8
  username: <%= ENV["DATABASE_USER"] %>
  password: <%= ENV["DATABASE_PASSWORD"] %>
  database: schedule
  pool: 5

development:
  <<: *default

test:
  <<: *default
  database: schedule_test

production:
  <<: *default
